apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth
  description: Сервис авторизации пользователей
  annotations:
    github.com/project-slug: s21platform/auth-service  # Укажите правильный репозиторий
#    backstage.io/techdocs-ref: dir:.  # Если планируете использовать TechDocs
  tags:
    - grpc
    - jwt
  links:
    - url: https://metric.x.space-21.ru/d/ceae9eguvvh8gf/auth-service?orgId=1&refresh=30s
      title: Grafana
      icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: auth-service-team  # GitHub-логин ответственного
  providesApis:
    - Login-v0
  consumesApis:
    - community-api
    - school-api
    - GetUserByLogin-v0
  dependsOn:
    - component:community
    - component:school
    - component:user
#  system: authentication-system  # Можно указать систему, если есть

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Login-v0
  description: Авторизация пользователя
  annotations:
    github.com/project-slug: s21platform/auth-service  # Укажите правильный репозиторий
  #    backstage.io/techdocs-ref: dir:.  # Если планируете использовать TechDocs
  tags:
    - proto
spec:
  type: grpc
  lifecycle: production
  owner: auth-service-team  # GitHub-логин ответственного
  definition: |
    rpc Login (LoginRequest) returns (LoginResponse) {};
    
    message LoginRequest {
        string username = 1;
        string password = 2;
    }
    
    message LoginResponse {
      string jwt = 1;
    }
