apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth
  description: Сервис авторизации пользователей
  annotations:
    github.com/project-slug: s21platform/auth-service  # Укажите правильный репозиторий
#    backstage.io/techdocs-ref: dir:.  # Если планируете использовать TechDocs
  tags:
    - grpc
    - jwt
  links:
    - url: https://metric.x.space-21.ru/d/ceae9eguvvh8gf/auth-service?orgId=1&refresh=30s
      title: Grafana
      icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: auth-service-team  # GitHub-логин ответственного
  providesApis:
    - auth-api  # API, который предоставляет сервис
  consumesApis:
    - community-api
    - school-api
    - user-v0-GetUserByLogin
  dependsOn:
    - component:community
    - component:school
    - component:user
#  system: authentication-system  # Можно указать систему, если есть