apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth
  description: Authentication and authorization service for the platform
  annotations:
    github.com/project-slug: s21platform/auth-service  # Укажите правильный репозиторий
#    backstage.io/techdocs-ref: dir:.  # Если планируете использовать TechDocs
  tags:
    - auth
    - security
    - jwt
spec:
  type: service
  lifecycle: production
  owner: alexseipopov  # GitHub-логин ответственного
  providesApis:
    - auth-api  # API, который предоставляет сервис
  consumesApis:
    - community-api
    - school-api
    - user-api
  dependsOn:
    - component:community
    - component:school
    - component:user
  system: authentication-system  # Можно указать систему, если есть