// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data for request JWT token for all access in our platform
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username can be just nickname or full email (nickanme@student.21-school.ru)
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// password from platform
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// response JWT token for access
type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// String with jwt
	Jwt           string `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type CheckEmailAvailabilityIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEmailAvailabilityIn) Reset() {
	*x = CheckEmailAvailabilityIn{}
	mi := &file_api_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEmailAvailabilityIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailAvailabilityIn) ProtoMessage() {}

func (x *CheckEmailAvailabilityIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailAvailabilityIn.ProtoReflect.Descriptor instead.
func (*CheckEmailAvailabilityIn) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CheckEmailAvailabilityIn) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CheckEmailAvailabilityOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable   bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEmailAvailabilityOut) Reset() {
	*x = CheckEmailAvailabilityOut{}
	mi := &file_api_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEmailAvailabilityOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailAvailabilityOut) ProtoMessage() {}

func (x *CheckEmailAvailabilityOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailAvailabilityOut.ProtoReflect.Descriptor instead.
func (*CheckEmailAvailabilityOut) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{3}
}

func (x *CheckEmailAvailabilityOut) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

// Data for save in pending table
type SendUserVerificationCodeIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// email to send code
	Email         string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUserVerificationCodeIn) Reset() {
	*x = SendUserVerificationCodeIn{}
	mi := &file_api_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUserVerificationCodeIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserVerificationCodeIn) ProtoMessage() {}

func (x *SendUserVerificationCodeIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserVerificationCodeIn.ProtoReflect.Descriptor instead.
func (*SendUserVerificationCodeIn) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{4}
}

func (x *SendUserVerificationCodeIn) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Response for SendCode
type SendUserVerificationCodeOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID of record from pending table
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUserVerificationCodeOut) Reset() {
	*x = SendUserVerificationCodeOut{}
	mi := &file_api_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUserVerificationCodeOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserVerificationCodeOut) ProtoMessage() {}

func (x *SendUserVerificationCodeOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserVerificationCodeOut.ProtoReflect.Descriptor instead.
func (*SendUserVerificationCodeOut) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{5}
}

func (x *SendUserVerificationCodeOut) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type RegisterUserIn struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Email           string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,3,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	Code            string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	CodeLookupUuid  string                 `protobuf:"bytes,5,opt,name=code_lookup_uuid,json=codeLookupUuid,proto3" json:"code_lookup_uuid,omitempty"` // UUID to look up the original verification code in pending_registrations
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterUserIn) Reset() {
	*x = RegisterUserIn{}
	mi := &file_api_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserIn) ProtoMessage() {}

func (x *RegisterUserIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserIn.ProtoReflect.Descriptor instead.
func (*RegisterUserIn) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterUserIn) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserIn) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserIn) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

func (x *RegisterUserIn) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterUserIn) GetCodeLookupUuid() string {
	if x != nil {
		return x.CodeLookupUuid
	}
	return ""
}

type LoginV2In struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginV2In) Reset() {
	*x = LoginV2In{}
	mi := &file_api_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginV2In) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginV2In) ProtoMessage() {}

func (x *LoginV2In) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginV2In.ProtoReflect.Descriptor instead.
func (*LoginV2In) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{7}
}

func (x *LoginV2In) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginV2In) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginV2Out struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginV2Out) Reset() {
	*x = LoginV2Out{}
	mi := &file_api_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginV2Out) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginV2Out) ProtoMessage() {}

func (x *LoginV2Out) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginV2Out.ProtoReflect.Descriptor instead.
func (*LoginV2Out) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{8}
}

func (x *LoginV2Out) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginV2Out) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// kafka contracts
type NewUserRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewUserRegister) Reset() {
	*x = NewUserRegister{}
	mi := &file_api_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewUserRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserRegister) ProtoMessage() {}

func (x *NewUserRegister) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserRegister.ProtoReflect.Descriptor instead.
func (*NewUserRegister) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{9}
}

func (x *NewUserRegister) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *NewUserRegister) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RefreshAccessTokenIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAccessTokenIn) Reset() {
	*x = RefreshAccessTokenIn{}
	mi := &file_api_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAccessTokenIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAccessTokenIn) ProtoMessage() {}

func (x *RefreshAccessTokenIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAccessTokenIn.ProtoReflect.Descriptor instead.
func (*RefreshAccessTokenIn) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshAccessTokenIn) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshAccessTokenOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAccessTokenOut) Reset() {
	*x = RefreshAccessTokenOut{}
	mi := &file_api_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAccessTokenOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAccessTokenOut) ProtoMessage() {}

func (x *RefreshAccessTokenOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAccessTokenOut.ProtoReflect.Descriptor instead.
func (*RefreshAccessTokenOut) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshAccessTokenOut) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

var File_api_auth_proto protoreflect.FileDescriptor

const file_api_auth_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/auth.proto\x1a\x1bgoogle/protobuf/empty.proto\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"!\n" +
	"\rLoginResponse\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\"0\n" +
	"\x18CheckEmailAvailabilityIn\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\">\n" +
	"\x19CheckEmailAvailabilityOut\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailable\"2\n" +
	"\x1aSendUserVerificationCodeIn\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"1\n" +
	"\x1bSendUserVerificationCodeOut\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\xab\x01\n" +
	"\x0eRegisterUserIn\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12)\n" +
	"\x10confirm_password\x18\x03 \x01(\tR\x0fconfirmPassword\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12(\n" +
	"\x10code_lookup_uuid\x18\x05 \x01(\tR\x0ecodeLookupUuid\"=\n" +
	"\tLoginV2In\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"T\n" +
	"\n" +
	"LoginV2Out\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"A\n" +
	"\x0fNewUserRegister\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\";\n" +
	"\x14RefreshAccessTokenIn\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\":\n" +
	"\x15RefreshAccessTokenOut\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken2\x8b\x03\n" +
	"\vAuthService\x12(\n" +
	"\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\"\x00\x12Q\n" +
	"\x16CheckEmailAvailability\x12\x19.CheckEmailAvailabilityIn\x1a\x1a.CheckEmailAvailabilityOut\"\x00\x12W\n" +
	"\x18SendUserVerificationCode\x12\x1b.SendUserVerificationCodeIn\x1a\x1c.SendUserVerificationCodeOut\"\x00\x129\n" +
	"\fRegisterUser\x12\x0f.RegisterUserIn\x1a\x16.google.protobuf.Empty\"\x00\x12$\n" +
	"\aLoginV2\x12\n" +
	".LoginV2In\x1a\v.LoginV2Out\"\x00\x12E\n" +
	"\x12RefreshAccessToken\x12\x15.RefreshAccessTokenIn\x1a\x16.RefreshAccessTokenOut\"\x00B\n" +
	"Z\bpkg/authb\x06proto3"

var (
	file_api_auth_proto_rawDescOnce sync.Once
	file_api_auth_proto_rawDescData []byte
)

func file_api_auth_proto_rawDescGZIP() []byte {
	file_api_auth_proto_rawDescOnce.Do(func() {
		file_api_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_proto_rawDesc), len(file_api_auth_proto_rawDesc)))
	})
	return file_api_auth_proto_rawDescData
}

var file_api_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),                // 0: LoginRequest
	(*LoginResponse)(nil),               // 1: LoginResponse
	(*CheckEmailAvailabilityIn)(nil),    // 2: CheckEmailAvailabilityIn
	(*CheckEmailAvailabilityOut)(nil),   // 3: CheckEmailAvailabilityOut
	(*SendUserVerificationCodeIn)(nil),  // 4: SendUserVerificationCodeIn
	(*SendUserVerificationCodeOut)(nil), // 5: SendUserVerificationCodeOut
	(*RegisterUserIn)(nil),              // 6: RegisterUserIn
	(*LoginV2In)(nil),                   // 7: LoginV2In
	(*LoginV2Out)(nil),                  // 8: LoginV2Out
	(*NewUserRegister)(nil),             // 9: NewUserRegister
	(*RefreshAccessTokenIn)(nil),        // 10: RefreshAccessTokenIn
	(*RefreshAccessTokenOut)(nil),       // 11: RefreshAccessTokenOut
	(*emptypb.Empty)(nil),               // 12: google.protobuf.Empty
}
var file_api_auth_proto_depIdxs = []int32{
	0,  // 0: AuthService.Login:input_type -> LoginRequest
	2,  // 1: AuthService.CheckEmailAvailability:input_type -> CheckEmailAvailabilityIn
	4,  // 2: AuthService.SendUserVerificationCode:input_type -> SendUserVerificationCodeIn
	6,  // 3: AuthService.RegisterUser:input_type -> RegisterUserIn
	7,  // 4: AuthService.LoginV2:input_type -> LoginV2In
	10, // 5: AuthService.RefreshAccessToken:input_type -> RefreshAccessTokenIn
	1,  // 6: AuthService.Login:output_type -> LoginResponse
	3,  // 7: AuthService.CheckEmailAvailability:output_type -> CheckEmailAvailabilityOut
	5,  // 8: AuthService.SendUserVerificationCode:output_type -> SendUserVerificationCodeOut
	12, // 9: AuthService.RegisterUser:output_type -> google.protobuf.Empty
	8,  // 10: AuthService.LoginV2:output_type -> LoginV2Out
	11, // 11: AuthService.RefreshAccessToken:output_type -> RefreshAccessTokenOut
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_proto_init() }
func file_api_auth_proto_init() {
	if File_api_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_proto_rawDesc), len(file_api_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_proto_goTypes,
		DependencyIndexes: file_api_auth_proto_depIdxs,
		MessageInfos:      file_api_auth_proto_msgTypes,
	}.Build()
	File_api_auth_proto = out.File
	file_api_auth_proto_goTypes = nil
	file_api_auth_proto_depIdxs = nil
}
