// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDBRepo is a mock of DBRepo interface.
type MockDBRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDBRepoMockRecorder
}

// MockDBRepoMockRecorder is the mock recorder for MockDBRepo.
type MockDBRepoMockRecorder struct {
	mock *MockDBRepo
}

// NewMockDBRepo creates a new mock instance.
func NewMockDBRepo(ctrl *gomock.Controller) *MockDBRepo {
	mock := &MockDBRepo{ctrl: ctrl}
	mock.recorder = &MockDBRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBRepo) EXPECT() *MockDBRepoMockRecorder {
	return m.recorder
}

// InsertPendingRegistration mocks base method.
func (m *MockDBRepo) InsertPendingRegistration(ctx context.Context, email, code string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPendingRegistration", ctx, email, code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPendingRegistration indicates an expected call of InsertPendingRegistration.
func (mr *MockDBRepoMockRecorder) InsertPendingRegistration(ctx, email, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPendingRegistration", reflect.TypeOf((*MockDBRepo)(nil).InsertPendingRegistration), ctx, email, code)
}

// IsEmailAvailable mocks base method.
func (m *MockDBRepo) IsEmailAvailable(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmailAvailable", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsEmailAvailable indicates an expected call of IsEmailAvailable.
func (mr *MockDBRepoMockRecorder) IsEmailAvailable(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmailAvailable", reflect.TypeOf((*MockDBRepo)(nil).IsEmailAvailable), ctx, email)
}

// MockSchoolS is a mock of SchoolS interface.
type MockSchoolS struct {
	ctrl     *gomock.Controller
	recorder *MockSchoolSMockRecorder
}

// MockSchoolSMockRecorder is the mock recorder for MockSchoolS.
type MockSchoolSMockRecorder struct {
	mock *MockSchoolS
}

// NewMockSchoolS creates a new mock instance.
func NewMockSchoolS(ctrl *gomock.Controller) *MockSchoolS {
	mock := &MockSchoolS{ctrl: ctrl}
	mock.recorder = &MockSchoolSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchoolS) EXPECT() *MockSchoolSMockRecorder {
	return m.recorder
}

// DoLogin mocks base method.
func (m *MockSchoolS) DoLogin(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoLogin", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoLogin indicates an expected call of DoLogin.
func (mr *MockSchoolSMockRecorder) DoLogin(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoLogin", reflect.TypeOf((*MockSchoolS)(nil).DoLogin), ctx, email, password)
}

// MockCommunityS is a mock of CommunityS interface.
type MockCommunityS struct {
	ctrl     *gomock.Controller
	recorder *MockCommunitySMockRecorder
}

// MockCommunitySMockRecorder is the mock recorder for MockCommunityS.
type MockCommunitySMockRecorder struct {
	mock *MockCommunityS
}

// NewMockCommunityS creates a new mock instance.
func NewMockCommunityS(ctrl *gomock.Controller) *MockCommunityS {
	mock := &MockCommunityS{ctrl: ctrl}
	mock.recorder = &MockCommunitySMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommunityS) EXPECT() *MockCommunitySMockRecorder {
	return m.recorder
}

// CheckPeer mocks base method.
func (m *MockCommunityS) CheckPeer(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPeer", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPeer indicates an expected call of CheckPeer.
func (mr *MockCommunitySMockRecorder) CheckPeer(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPeer", reflect.TypeOf((*MockCommunityS)(nil).CheckPeer), ctx, email)
}

// MockUserS is a mock of UserS interface.
type MockUserS struct {
	ctrl     *gomock.Controller
	recorder *MockUserSMockRecorder
}

// MockUserSMockRecorder is the mock recorder for MockUserS.
type MockUserSMockRecorder struct {
	mock *MockUserS
}

// NewMockUserS creates a new mock instance.
func NewMockUserS(ctrl *gomock.Controller) *MockUserS {
	mock := &MockUserS{ctrl: ctrl}
	mock.recorder = &MockUserSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserS) EXPECT() *MockUserSMockRecorder {
	return m.recorder
}

// GetOrSetUser mocks base method.
func (m *MockUserS) GetOrSetUser(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrSetUser", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrSetUser indicates an expected call of GetOrSetUser.
func (mr *MockUserSMockRecorder) GetOrSetUser(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrSetUser", reflect.TypeOf((*MockUserS)(nil).GetOrSetUser), ctx, email)
}

// MockNotificationS is a mock of NotificationS interface.
type MockNotificationS struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationSMockRecorder
}

// MockNotificationSMockRecorder is the mock recorder for MockNotificationS.
type MockNotificationSMockRecorder struct {
	mock *MockNotificationS
}

// NewMockNotificationS creates a new mock instance.
func NewMockNotificationS(ctrl *gomock.Controller) *MockNotificationS {
	mock := &MockNotificationS{ctrl: ctrl}
	mock.recorder = &MockNotificationSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationS) EXPECT() *MockNotificationSMockRecorder {
	return m.recorder
}

// SendVerificationCode mocks base method.
func (m *MockNotificationS) SendVerificationCode(ctx context.Context, email, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationCode", ctx, email, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVerificationCode indicates an expected call of SendVerificationCode.
func (mr *MockNotificationSMockRecorder) SendVerificationCode(ctx, email, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationCode", reflect.TypeOf((*MockNotificationS)(nil).SendVerificationCode), ctx, email, code)
}
